CREATE TABLE [dbo].[CARRITOS] (
    [CODPIEZA] NVARCHAR (7) NOT NULL,
    [CANTIDAD] INT          NOT NULL,
    [CODCLI]   FLOAT (53)   NOT NULL,
    [FECHA]    DATETIME     NOT NULL,
    CONSTRAINT [PK_CARRITO] PRIMARY KEY CLUSTERED ([CODPIEZA] ASC, [CODCLI] ASC)
);

