CREATE TABLE [dbo].[CLIENTES_CONFIGURACIONES] (
    [CODCLI]    INT             NOT NULL,
    [BENEFICIO] DECIMAL (18, 4) CONSTRAINT [DF_CLIENTES_CONFIGURACIONES_BENEFICIO] DEFAULT ((0)) NOT NULL,
    [DESCUENTO] DECIMAL (18, 4) CONSTRAINT [DF_CLIENTES_CONFIGURACIONES_DESCUENTO] DEFAULT ((0)) NOT NULL,
    [IVA]       BIT             CONSTRAINT [DF_CLIENTES_CONFIGURACIONES_IVA] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CLIENTES_CONFIGURACIONES] PRIMARY KEY CLUSTERED ([CODCLI] ASC)
);

