CREATE TABLE [dbo].[INICIOS_SESION] (
    [CODCLI]          INT            NOT NULL,
    [FECHA]           DATETIME       NOT NULL,
    [TIPO_CATALOGO]   NVARCHAR (50)  NOT NULL,
    [EMAIL]           NVARCHAR (256) NULL,
    [PC]              NVARCHAR (80)  NULL,
    [USUARIO]         NVARCHAR (250) NULL,
    [CODCLI_ANTERIOR] INT            NULL,
    CONSTRAINT [PK_INICIOS_SESION] PRIMARY KEY CLUSTERED ([CODCLI] ASC, [FECHA] ASC, [TIPO_CATALOGO] ASC)
);

