CREATE TABLE [dbo].[RUBRO_PARAMETRO] (
    [RUB_CODIGO] INT           NOT NULL,
    [PARA1_N]    NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA2_N]    NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA3_N]    NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA4_N]    NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA5_N]    NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA6_N]    NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA7_N]    NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA8_N]    NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA9_N]    NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA10_N]   NVARCHAR (50) DEFAULT (NULL) NULL,
    [PARA1_I]    NVARCHAR (1)  DEFAULT (NULL) NULL,
    [PARA2_I]    NVARCHAR (1)  DEFAULT (NULL) NULL,
    [PARA3_I]    NVARCHAR (1)  DEFAULT (NULL) NULL,
    [PARA4_I]    NVARCHAR (1)  DEFAULT (NULL) NULL,
    [PARA5_I]    NVARCHAR (1)  DEFAULT (NULL) NULL,
    [PARA6_I]    NVARCHAR (1)  DEFAULT (NULL) NULL,
    [PARA7_I]    NVARCHAR (1)  DEFAULT (NULL) NULL,
    [PARA8_I]    NVARCHAR (1)  DEFAULT (NULL) NULL,
    [PARA9_I]    NVARCHAR (1)  DEFAULT (NULL) NULL,
    [PARA10_I]   NVARCHAR (1)  DEFAULT (NULL) NULL
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'autocor.rubro_parametro', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'RUBRO_PARAMETRO';

