//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AutocorApi.Servicios.AutocorEmailTestWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AutocorWebServicesBinding", Namespace="http://www.autocor.com.ar/soap/AutocorWebServices")]
    public partial class AutocorWebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mailConsultasOperationCompleted;
        
        private System.Threading.SendOrPostCallback mailHtmlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AutocorWebServices() {
            this.Url = global::AutocorApi.Servicios.Properties.Settings.Default.AutocorApi_Servicios_AutocorEmailTestWS_AutocorWebServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mailConsultasCompletedEventHandler mailConsultasCompleted;
        
        /// <remarks/>
        public event mailHtmlCompletedEventHandler mailHtmlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.autocor.com.ar/serviciosWeb/test/ws.php/mailConsultas", RequestNamespace="http://www.autocor.com.ar/serviciosWeb/test", ResponseNamespace="http://www.autocor.com.ar/serviciosWeb/test")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool mailConsultas(string name, string email, string msj, string asunto, string t) {
            object[] results = this.Invoke("mailConsultas", new object[] {
                        name,
                        email,
                        msj,
                        asunto,
                        t});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void mailConsultasAsync(string name, string email, string msj, string asunto, string t) {
            this.mailConsultasAsync(name, email, msj, asunto, t, null);
        }
        
        /// <remarks/>
        public void mailConsultasAsync(string name, string email, string msj, string asunto, string t, object userState) {
            if ((this.mailConsultasOperationCompleted == null)) {
                this.mailConsultasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmailConsultasOperationCompleted);
            }
            this.InvokeAsync("mailConsultas", new object[] {
                        name,
                        email,
                        msj,
                        asunto,
                        t}, this.mailConsultasOperationCompleted, userState);
        }
        
        private void OnmailConsultasOperationCompleted(object arg) {
            if ((this.mailConsultasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mailConsultasCompleted(this, new mailConsultasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.autocor.com.ar/serviciosWeb/test/ws.php/mailHtml", RequestNamespace="http://www.autocor.com.ar/serviciosWeb/test", ResponseNamespace="http://www.autocor.com.ar/serviciosWeb/test")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool mailHtml(string mensajeHtml, string reply, string asunto, string destino) {
            object[] results = this.Invoke("mailHtml", new object[] {
                        mensajeHtml,
                        reply,
                        asunto,
                        destino});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void mailHtmlAsync(string mensajeHtml, string reply, string asunto, string destino) {
            this.mailHtmlAsync(mensajeHtml, reply, asunto, destino, null);
        }
        
        /// <remarks/>
        public void mailHtmlAsync(string mensajeHtml, string reply, string asunto, string destino, object userState) {
            if ((this.mailHtmlOperationCompleted == null)) {
                this.mailHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmailHtmlOperationCompleted);
            }
            this.InvokeAsync("mailHtml", new object[] {
                        mensajeHtml,
                        reply,
                        asunto,
                        destino}, this.mailHtmlOperationCompleted, userState);
        }
        
        private void OnmailHtmlOperationCompleted(object arg) {
            if ((this.mailHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mailHtmlCompleted(this, new mailHtmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void mailConsultasCompletedEventHandler(object sender, mailConsultasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mailConsultasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mailConsultasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void mailHtmlCompletedEventHandler(object sender, mailHtmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mailHtmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mailHtmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591